
# I basically only have this file so I can use 'make'
# instead of the longer python command below. setup.py
# compiles the c modules into a shared object (.so) 

all:
	python setup.py build_ext --inplace
